name = "foresight-analyzer-api"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Account details
account_id = "a867271c1fc772b3fbd26f1c347892ff"

[env.production]
name = "foresight-analyzer-api"
workers_dev = false

# Durable Objects for job management (requires paid plan - commented out for now)
# [[durable_objects.bindings]]
# name = "FORECAST_PROCESSOR"
# class_name = "ForecastProcessor"
# script_name = "foresight-analyzer-api"

# [[migrations]]
# tag = "v1"
# new_sqlite_classes = ["ForecastProcessor"]

# KV Namespaces for caching
[[kv_namespaces]]
binding = "FORECAST_CACHE"
id = "861ba6d6fe9448d09a058405fa8d34a1"

# R2 Buckets for Excel file storage (optional - uncomment when needed)
# [[r2_buckets]]
# binding = "FORECAST_RESULTS"
# bucket_name = "foresight-results"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Secrets (use wrangler secret put to set these)
# OPENROUTER_API_KEY
# BACKEND_URL (optional external FastAPI service)

# Routes will be automatically assigned by Cloudflare
