# Cloudflare Worker Configuration for API Proxy
name = "foresight-api-proxy"
main = "api-proxy-worker.js"
compatibility_date = "2024-01-01"

# Account details
account_id = "a867271c1fc772b3fbd26f1c347892ff"
